AWSTemplateFormatVersion: "2010-09-09"
Description: WAGUWAGU Tokyo CloudWatch + DR (EKS NodeGroup ID based)

Parameters:
  ProjectPrefix:
    Type: String
    Default: T3-Wagu-DR

  GameNodeASG:
    Type: String
    Description: EKS Game NodeGroup ASG ID (Tokyo)

  MatchingNodeASG:
    Type: String
    Description: EKS Matching NodeGroup ASG ID (Tokyo)

  AuroraClusterId:
    Type: String
    Default: wagu-dr-aurora-cluster

  AlarmEmail:
    Type: String
    Default: xyukyeong@naver.com

Resources:
  ############################################################
  # Dashboard
  ############################################################
  TokyoDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${ProjectPrefix}-Tokyo-Infra-Dashboard"
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                {
                  "type": "metric",
                  "x": 0,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "CPU Utilization (Tokyo)",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/EC2","CPUUtilization","AutoScalingGroupName","${GameNG}",{"stat":"Average"}],
                      ["AWS/EC2","CPUUtilization","AutoScalingGroupName","${MatchingNG}",{"stat":"Average"}]
                    ],
                    "period": 300
                  }
                },

                {
                  "type": "metric",
                  "x": 12,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "ASG Desired vs InService (Tokyo)",
                    "view": "timeSeries",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/AutoScaling","GroupDesiredCapacity","AutoScalingGroupName","${GameNG}",{"label":"Game Desired"}],
                      [".","GroupInServiceInstances",".",".",{"label":"Game InService"}],
                      [".","GroupDesiredCapacity",".","${MatchingNG}",{"label":"Matching Desired"}],
                      [".","GroupInServiceInstances",".",".",{"label":"Matching InService"}]
                    ],
                    "period": 300
                  }
                },

                {
                  "type": "metric",
                  "x": 0,
                  "y": 6,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "EC2 Status Check Failed (Tokyo)",
                    "view": "timeSeries",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/EC2","StatusCheckFailed","AutoScalingGroupName","${GameNG}",{"stat":"Maximum","label":"Game Nodes"}],
                      [".",".",".","${MatchingNG}",{"stat":"Maximum","label":"Matching Nodes"}]
                    ],
                    "period": 60
                  }
                },

                {
                  "type": "metric",
                  "x": 12,
                  "y": 6,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "ASG Scaling Activity (Tokyo)",
                    "view": "timeSeries",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/AutoScaling","GroupPendingInstances","AutoScalingGroupName","${GameNG}",{"label":"Game Pending"}],
                      [".","GroupTerminatingInstances",".",".",{"label":"Game Terminating"}],
                      [".","GroupPendingInstances",".","${MatchingNG}",{"label":"Matching Pending"}],
                      [".","GroupTerminatingInstances",".",".",{"label":"Matching Terminating"}]
                    ],
                    "period": 300
                  }
                },

                {
                  "type": "metric",
                  "x": 0,
                  "y": 12,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "Aurora CPU (Tokyo)",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/RDS","CPUUtilization","DBClusterIdentifier","${AuroraId}"]
                    ],
                    "period": 300
                  }
                },

                {
                  "type": "metric",
                  "x": 12,
                  "y": 12,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "Aurora Replica Lag (Tokyo)",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/RDS","AuroraReplicaLag","DBClusterIdentifier","${AuroraId}"]
                    ],
                    "period": 60
                  }
                },

                {
                  "type": "metric",
                  "x": 0,
                  "y": 18,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "NAT Gateway Traffic (Game - Tokyo)",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/NATGateway","BytesInFromSource","NatGatewayId","${GameNat}",{"stat":"Sum"}],
                      [".","BytesOutToDestination",".","."]
                    ],
                    "period": 300
                  }
                },

                {
                  "type": "metric",
                  "x": 12,
                  "y": 18,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "NAT Gateway Traffic (Matching - Tokyo)",
                    "region": "ap-northeast-1",
                    "metrics": [
                      ["AWS/NATGateway","BytesInFromSource","NatGatewayId","${MatchingNat}",{"stat":"Sum"}],
                      [".","BytesOutToDestination",".","."]
                    ],
                    "period": 300
                  }
                }
              ]
            }

          - GameNG: !Ref GameNodeASG
            MatchingNG: !Ref MatchingNodeASG
            AuroraId: !Ref AuroraClusterId
            GameNat: !ImportValue T3-Wagu-DR-Game-NAT-GW-Id
            MatchingNat: !ImportValue T3-Wagu-DR-Matching-NAT-GW-Id

  ############################################################
  # SNS
  ############################################################
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectPrefix}-Tokyo-Infra-Alarms"

  AlarmEmailSub:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmSNSTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail

  ############################################################
  # Aurora Alarm
  ############################################################
  AuroraLagAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectPrefix}-Aurora-ReplicaLag"
      Namespace: AWS/RDS
      MetricName: AuroraReplicaLag
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraClusterId
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref AlarmSNSTopic]
