AWSTemplateFormatVersion: "2010-09-09"
Description: "WAGUWAGU CloudWatch Dashboard - Service Infra Monitoring (Infra Focus)"

Parameters:
  ProjectPrefix:
    Type: String
    Default: T3-Wagu

  GameNodeASG:
    Type: String

  MatchingNodeASG:
    Type: String

Resources:
  InfraDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${ProjectPrefix}-Infra-Dashboard"
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                {
                  "type": "metric",
                  "x": 0,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "CPU Utilization - Game vs Matching",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "annotations": {
                      "horizontal": [
                        { "label": "Warning (50%)", "value": 50 }
                      ]
                    },
                    "metrics": [
                      [ "AWS/EC2", "CPUUtilization", "AutoScalingGroupName", "${GameASG}", { "label": "Game CPU", "stat": "Average" } ],
                      [ ".", ".", ".", "${MatchingASG}", { "label": "Matching CPU", "stat": "Average" } ]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "x": 12,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "ASG Desired vs InService",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      [ "AWS/AutoScaling", "GroupDesiredCapacity", "AutoScalingGroupName", "${GameASG}", { "label": "Game Desired" } ],
                      [ ".", "GroupInServiceInstances", ".", ".", { "label": "Game InService" } ],
                      [ ".", "GroupDesiredCapacity", ".", "${MatchingASG}", { "label": "Matching Desired" } ],
                      [ ".", "GroupInServiceInstances", ".", ".", { "label": "Matching InService" } ]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 6,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "Network Traffic (Game Nodes)",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      [ "AWS/EC2", "NetworkIn", "AutoScalingGroupName", "${GameASG}", { "label": "In", "stat": "Sum" } ],
                      [ ".", "NetworkOut", ".", ".", { "label": "Out", "stat": "Sum" } ]
                    ]
                  }
                },

                {
                  "type": "metric",
                  "x": 12,
                  "y": 6,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "Network Traffic (Matching Nodes)",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      [ "AWS/EC2", "NetworkIn", "AutoScalingGroupName", "${MatchingASG}", { "label": "In", "stat": "Sum" } ],
                      [ ".", "NetworkOut", ".", ".", { "label": "Out", "stat": "Sum" } ]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 12,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "EC2 Status Check Failed",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      [ "AWS/EC2", "StatusCheckFailed", "AutoScalingGroupName", "${GameASG}", { "label": "Game Nodes", "stat": "Maximum" } ],
                      [ ".", ".", ".", "${MatchingASG}", { "label": "Matching Nodes", "stat": "Maximum" } ]
                    ]
                  }
                },
                                {
                  "type": "metric",
                  "x": 12,
                  "y": 12,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "ASG Scaling Activity (Pending / Terminating)",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      [ "AWS/AutoScaling", "GroupPendingInstances", "AutoScalingGroupName", "${GameASG}", { "label": "Game Pending" } ],
                      [ ".", "GroupTerminatingInstances", ".", ".", { "label": "Game Terminating" } ],
                      [ ".", "GroupPendingInstances", ".", "${MatchingASG}", { "label": "Matching Pending" } ],
                      [ ".", "GroupTerminatingInstances", ".", ".", { "label": "Matching Terminating" } ]
                    ]
                  }
                }
              ]
            }
          - GameASG: !Ref GameNodeASG
            MatchingASG: !Ref MatchingNodeASG
