AWSTemplateFormatVersion: "2010-09-09"
Description: Wagu Production Aurora MySQL Global Database - Primary (Seoul)

Parameters:
  DBName:
    Type: String
    Default: wagudb

  DBInstanceClass:
    Type: String
    Default: db.r6g.large

  MasterUsername:
    Type: String
    Default: wagu_admin
    AllowedPattern: "[a-zA-Z0-9_]+"

  MasterPassword:
    Type: String
    NoEcho: true
    
Resources:
  # 1. Security Group
  WaguAuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from App VPC
      VpcId: !ImportValue T3-Wagu-Matching-VPC-Id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16

  # 2. Subnet Group
  WaguAuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Aurora subnet group
      SubnetIds: !Split
        - ","
        - !ImportValue T3-Wagu-Matching-Private-Db-Subnet-Ids

  # 3. Parameter Group (Aurora MySQL)
  WaguAuroraParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Family: aurora-mysql8.0
      Description: Aurora MySQL parameter group
      Parameters:
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci
        time_zone: Asia/Seoul

  # 4. Global Database
  WaguGlobalDatabase:
    Type: AWS::RDS::GlobalCluster
    Properties:
      GlobalClusterIdentifier: wagu-global-db
      Engine: aurora-mysql
      EngineVersion: "8.0.mysql_aurora.3.04.0"

  # 5. Primary Cluster
  WaguAuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: wagu-prod-aurora-cluster
      Engine: aurora-mysql
      EngineVersion: "8.0.mysql_aurora.3.04.0"
      DatabaseName: !Ref DBName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword
      DBSubnetGroupName: !Ref WaguAuroraSubnetGroup
      VpcSecurityGroupIds:
        - !Ref WaguAuroraSecurityGroup
      DBClusterParameterGroupName: !Ref WaguAuroraParameterGroup
      GlobalClusterIdentifier: !Ref WaguGlobalDatabase
      BackupRetentionPeriod: 7
      DeletionProtection: false

  # 6. Writer Instance
  WaguAuroraWriter:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: wagu-prod-aurora-writer
      DBClusterIdentifier: !Ref WaguAuroraCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false