AWSTemplateFormatVersion: "2010-09-09"
Description: "WaguWagu Project: S3 Bucket Setup"

Resources:
  # ============================================================
  # Common WaguWagu S3 Bucket
  # ============================================================
  WaguWaguBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "t3-wagu-s3-bucket-seoul"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: t3-wagu-s3-bucket-seoul

  # ============================================================
  # Loki Log Storage S3 Bucket (NEW)
  # ============================================================
  LokiLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "t3-wagu-loki-logs-seoul"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: t3-wagu-loki-logs-seoul
        - Key: Purpose
          Value: loki-log-storage

  # ============================================================
  # CloudTrail Log Storage S3 Bucket
  # ============================================================
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "t3-wagu-cloudtrail-logs-seoul"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: t3-wagu-cloudtrail-logs
        - Key: Purpose
          Value: cloudtrail-audit-logs

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${CloudTrailBucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSCloudTrailRead
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailBucket.Arn


Outputs:
  # ============================================================
  # Common Bucket Outputs
  # ============================================================
  BucketName:
    Description: WaguWagu S3 Bucket Name
    Value: !Ref WaguWaguBucket
    Export:
      Name: t3-wagu-s3-bucket

  BucketArn:
    Description: WaguWagu S3 Bucket ARN
    Value: !GetAtt WaguWaguBucket.Arn
    Export:
      Name: t3-wagu-s3-bucket-arn

  # ============================================================
  # Loki Bucket Outputs (NEW)
  # ============================================================
  LokiBucketName:
    Description: Loki Logs S3 Bucket Name
    Value: !Ref LokiLogsBucket
    Export:
      Name: t3-wagu-loki-s3-bucket

  LokiBucketArn:
    Description: Loki Logs S3 Bucket ARN
    Value: !GetAtt LokiLogsBucket.Arn
    Export:
      Name: t3-wagu-loki-s3-bucket-arn

  # ============================================================
  # CloudTrail Bucket Outputs
  # ============================================================
  CloudTrailBucketName:
    Description: CloudTrail Logs S3 Bucket Name
    Value: !Ref CloudTrailBucket
    Export:
      Name: t3-wagu-cloudtrail-bucket-name

  CloudTrailBucketArn:
    Description: CloudTrail Logs S3 Bucket ARN
    Value: !GetAtt CloudTrailBucket.Arn
    Export:
      Name: t3-wagu-cloudtrail-bucket-arn