AWSTemplateFormatVersion: "2010-09-09"
Description: WAGUWAGU Seoul CloudWatch Infra (ASG via Parameters)

Parameters:
  ProjectPrefix:
    Type: String
    Default: T3-Wagu

  GameNodeASGName:
    Type: String
    Description: Seoul Game ASG Name

  MatchingNodeASGName:
    Type: String
    Description: Seoul Matching ASG Name

  AlarmEmail:
    Type: String
    Default: xyukyeong@naver.com

Resources:
  ############################################################
  # Dashboard
  ############################################################
  SeoulDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${ProjectPrefix}-Seoul-Infra-Dashboard"
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                {
                  "type": "metric",
                  "x": 0,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "CPU Utilization (Seoul)",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      ["AWS/EC2","CPUUtilization","AutoScalingGroupName","${GameASG}",{"label":"Game","stat":"Average"}],
                      ["AWS/EC2","CPUUtilization","AutoScalingGroupName","${MatchingASG}",{"label":"Matching","stat":"Average"}]
                    ],
                    "period": 300
                  }
                },
                {
                  "type": "metric",
                  "x": 12,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "title": "ASG Desired vs InService (Seoul)",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      ["AWS/AutoScaling","GroupDesiredCapacity","AutoScalingGroupName","${GameASG}"],
                      [".","GroupInServiceInstances",".","."],
                      [".","GroupDesiredCapacity",".","${MatchingASG}"],
                      [".","GroupInServiceInstances",".","."]
                    ],
                    "period": 300
                  }
                },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 6,
                  "width": 24,
                  "height": 6,
                  "properties": {
                    "title": "NAT Gateway Traffic (Seoul)",
                    "view": "timeSeries",
                    "region": "ap-northeast-2",
                    "metrics": [
                      ["AWS/NATGateway","BytesInFromSource","NatGatewayId","${GameNatId}",{"stat":"Sum"}],
                      [".","BytesOutToDestination",".","."],
                      [".","BytesInFromSource","NatGatewayId","${MatchingNatId}",{"stat":"Sum"}],
                      [".","BytesOutToDestination",".","."]
                    ],
                    "period": 300
                  }
                }
              ]
            }
          - GameASG: !Ref GameNodeASGName
            MatchingASG: !Ref MatchingNodeASGName
            GameNatId: !ImportValue
              Fn::Sub: "${ProjectPrefix}-Game-NAT-GW-Id"
            MatchingNatId: !ImportValue
              Fn::Sub: "${ProjectPrefix}-Matching-NAT-GW-Id"

  ############################################################
  # Alarm SNS
  ############################################################
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectPrefix}-Seoul-Infra-Alarms"

  AlarmEmailSub:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmSNSTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail

  ############################################################
  # Alarms
  ############################################################
  GameCPUHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectPrefix}-Seoul-Game-CPU-High"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref GameNodeASGName
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions: [!Ref AlarmSNSTopic]

  MatchingCPUHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectPrefix}-Seoul-Matching-CPU-High"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref MatchingNodeASGName
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions: [!Ref AlarmSNSTopic]
